<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RunOrNope.Broker.Windows\RunOrNope.Broker.Windows.csproj" />
    <ProjectReference Include="..\RunOrNope.Contracts\RunOrNope.Contracts.csproj" />
    <ProjectReference Include="..\RunOrNope.Core\RunOrNope.Core.csproj" />
    <ProjectReference Include="..\RunOrNope.Intake\RunOrNope.Intake.csproj" />
    <ProjectReference Include="..\RunOrNope.Reporting\RunOrNope.Reporting.csproj" />
  </ItemGroup>
</Project>
